CC = gcc

CFLAGS  = -g -Wall

DISASSEMBLER = 8080dis
EMULATOR = 8080emu

all: $(DISASSEMBLER) $(EMULATOR)
$(DISASSEMBLER): $(DISASSEMBLER).c
	$(CC) $(CFLAGS) -o $(DISASSEMBLER) $(DISASSEMBLER).c
$(EMULATOR): $(EMULATOR).c
	$(CC) $(CFLAGS) -o $(EMULATOR) $(EMULATOR).c

clean:
	$(RM) $(DISASSEMBLER) $(EMULATOR)